Add VPN support to all containers. Based on gluetun

diff --git a/templates/apps/apprise/deployment.yaml b/templates/apps/apprise/deployment.yaml
--- a/templates/apps/apprise/deployment.yaml
+++ b/templates/apps/apprise/deployment.yaml
@@ -21,6 +21,46 @@ spec:
     spec:
       securityContext:
         fsGroup: {{ required "A valid GID required!" .Values.host.gid }}
+      initContainers:
+      {{- if .Values.services.apprise.vpn.enabled }}
+        - name: gluetun
+          image: ghcr.io/qdm12/gluetun:v3.40
+          imagePullPolicy: IfNotPresent
+          restartPolicy: Always
+          securityContext:
+            capabilities:
+              add: ["NET_ADMIN"]
+          env:
+            - name: TZ
+              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
+            - name: VPN_SERVICE_PROVIDER
+              value: custom
+            - name: VPN_TYPE
+              value: wireguard
+            - name: HTTP_CONTROL_SERVER_ADDRESS
+              value: ":8001"
+            - name: DNS_KEEP_NAMESERVER
+              value: "on"
+            - name: FIREWALL_OUTBOUND_SUBNETS
+              value: "10.42.0.0/15"
+          volumeMounts:
+            - name: wg0-conf
+              mountPath: /gluetun/wireguard/
+              readOnly: true
+            - name: dev-net-tun
+              mountPath: /dev/net/tun
+        - name: verify-vpn
+          image: busybox
+          command:
+            - sh
+            - -c
+            - |
+              while ! ping -c 1 8.8.8.8; do
+                echo "Ping failed, retrying in 5"
+                sleep 5
+              done
+              echo "VPN connection established successfully, exiting"
+      {{- end }}
       containers:
         - name: apprise
           image: "{{ .Values.services.apprise.image.repository }}:{{ .Values.services.apprise.image.tag }}"
@@ -47,7 +87,7 @@ spec:
             - name: APPRISE_DEFAULT_CONFIG_ID
               value: {{ .Values.services.apprise.defaultConfigId | quote }}
             - name: ALLOWED_HOSTS
-              value: "{{ .Values.services.apprise.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}"
+              value: "{{ .Values.services.apprise.name }},{{ .Values.services.apprise.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}"
           ports:
             - name: http
               containerPort: 8000
@@ -58,6 +98,16 @@ spec:
             - name: attachments
               mountPath: /attachments
       volumes:
+        {{- if .Values.services.apprise.vpn.enabled }}
+        - name: wg0-conf
+          secret:
+            secretName: gluetun-wireguard-conf
+            optional: false
+        - name: dev-net-tun
+          hostPath:
+            path: /dev/net/tun
+            type: CharDevice
+        {{- end }}
         - name: config
           hostPath:
             path: "{{ .Values.services.apprise.config }}"
diff --git a/templates/apps/flaresolverr/deployment.yaml b/templates/apps/flaresolverr/deployment.yaml
--- a/templates/apps/flaresolverr/deployment.yaml
+++ b/templates/apps/flaresolverr/deployment.yaml
@@ -19,6 +19,46 @@ spec:
       labels:
         app.kubernetes.io/name: {{ .Values.services.flaresolverr.name }}
     spec:
+      initContainers:
+      {{- if .Values.services.flaresolverr.vpn.enabled }}
+        - name: gluetun
+          image: ghcr.io/qdm12/gluetun:v3.40
+          imagePullPolicy: IfNotPresent
+          restartPolicy: Always
+          securityContext:
+            capabilities:
+              add: ["NET_ADMIN"]
+          env:
+            - name: TZ
+              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
+            - name: VPN_SERVICE_PROVIDER
+              value: custom
+            - name: VPN_TYPE
+              value: wireguard
+            - name: HTTP_CONTROL_SERVER_ADDRESS
+              value: ":8001"
+            - name: DNS_KEEP_NAMESERVER
+              value: "on"
+            - name: FIREWALL_OUTBOUND_SUBNETS
+              value: "10.42.0.0/15"
+          volumeMounts:
+            - name: wg0-conf
+              mountPath: /gluetun/wireguard/
+              readOnly: true
+            - name: dev-net-tun
+              mountPath: /dev/net/tun
+        - name: verify-vpn
+          image: busybox
+          command:
+            - sh
+            - -c
+            - |
+              while ! ping -c 1 8.8.8.8; do
+                echo "Ping failed, retrying in 5"
+                sleep 5
+              done
+              echo "VPN connection established successfully, exiting"
+      {{- end }}
       containers:
         - name: flaresolverr
           image: "{{ .Values.services.flaresolverr.image.repository }}:{{ .Values.services.flaresolverr.image.tag }}"
@@ -34,14 +74,25 @@ spec:
               value: {{ required "A valid GID required!" .Values.host.gid | quote }}
             - name: TZ
               value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
+            - name: DRIVER
+              value: {{ .Values.services.flaresolverr.driver | quote }}
             - name: LOG_LEVEL
               value: {{ .Values.services.flaresolverr.logLevel | quote }}
             - name: LANG
               value: {{ .Values.services.flaresolverr.lang | quote }}
-            - name: CAPTCHA_SOLVER
-              value: {{ .Values.services.flaresolverr.captchaSolver | quote }}
           ports:
             - name: http
               containerPort: 8191
               protocol: TCP
+      volumes:
+        {{- if .Values.services.flaresolverr.vpn.enabled }}
+        - name: wg0-conf
+          secret:
+            secretName: gluetun-wireguard-conf
+            optional: false
+        - name: dev-net-tun
+          hostPath:
+            path: /dev/net/tun
+            type: CharDevice
+        {{- end }}
 {{- end}}
diff --git a/templates/apps/plex/deployment.yaml b/templates/apps/plex/deployment.yaml
--- a/templates/apps/plex/deployment.yaml
+++ b/templates/apps/plex/deployment.yaml
@@ -20,6 +20,46 @@ spec:
         app.kubernetes.io/name: {{ .Values.services.plex.name }}
     spec:
       priorityClassName: homeserver-high-priority
+      initContainers:
+      {{- if .Values.services.plex.vpn.enabled }}
+        - name: gluetun
+          image: ghcr.io/qdm12/gluetun:v3.40
+          imagePullPolicy: IfNotPresent
+          restartPolicy: Always
+          securityContext:
+            capabilities:
+              add: ["NET_ADMIN"]
+          env:
+            - name: TZ
+              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
+            - name: VPN_SERVICE_PROVIDER
+              value: custom
+            - name: VPN_TYPE
+              value: wireguard
+            - name: HTTP_CONTROL_SERVER_ADDRESS
+              value: ":8001"
+            - name: DNS_KEEP_NAMESERVER
+              value: "on"
+            - name: FIREWALL_OUTBOUND_SUBNETS
+              value: "10.42.0.0/15"
+          volumeMounts:
+            - name: wg0-conf
+              mountPath: /gluetun/wireguard/
+              readOnly: true
+            - name: dev-net-tun
+              mountPath: /dev/net/tun
+        - name: verify-vpn
+          image: busybox
+          command:
+            - sh
+            - -c
+            - |
+              while ! ping -c 1 8.8.8.8; do
+                echo "Ping failed, retrying in 5"
+                sleep 5
+              done
+              echo "VPN connection established successfully, exiting"
+      {{- end }}
       containers:
         - name: plex
           image: "{{ .Values.services.plex.image.repository }}:{{ .Values.services.plex.image.tag }}"
@@ -47,6 +87,16 @@ spec:
             - name: library
               mountPath: "{{ .Values.services.plex.library }}"
       volumes:
+        {{- if .Values.services.plex.vpn.enabled }}
+        - name: wg0-conf
+          secret:
+            secretName: gluetun-wireguard-conf
+            optional: false
+        - name: dev-net-tun
+          hostPath:
+            path: /dev/net/tun
+            type: CharDevice
+        {{- end }}
         - name: config
           hostPath:
             path: "{{ .Values.services.plex.config }}"
diff --git a/templates/backrest/deployment.yaml b/templates/backrest/deployment.yaml
--- a/templates/backrest/deployment.yaml
+++ b/templates/backrest/deployment.yaml
@@ -19,6 +19,46 @@ spec:
       labels:
         app.kubernetes.io/name: {{ .Values.services.backrest.name }}
     spec:
+      initContainers:
+      {{- if .Values.services.backrest.vpn.enabled }}
+        - name: gluetun
+          image: ghcr.io/qdm12/gluetun:v3.40
+          imagePullPolicy: IfNotPresent
+          restartPolicy: Always
+          securityContext:
+            capabilities:
+              add: ["NET_ADMIN"]
+          env:
+            - name: TZ
+              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
+            - name: VPN_SERVICE_PROVIDER
+              value: custom
+            - name: VPN_TYPE
+              value: wireguard
+            - name: HTTP_CONTROL_SERVER_ADDRESS
+              value: ":8001"
+            - name: DNS_KEEP_NAMESERVER
+              value: "on"
+            - name: FIREWALL_OUTBOUND_SUBNETS
+              value: "10.42.0.0/15"
+          volumeMounts:
+            - name: wg0-conf
+              mountPath: /gluetun/wireguard/
+              readOnly: true
+            - name: dev-net-tun
+              mountPath: /dev/net/tun
+        - name: verify-vpn
+          image: busybox
+          command:
+            - sh
+            - -c
+            - |
+              while ! ping -c 1 8.8.8.8; do
+                echo "Ping failed, retrying in 5"
+                sleep 5
+              done
+              echo "VPN connection established successfully, exiting"
+      {{- end }}
       containers:
         - name: backrest
           image: "{{ .Values.services.backrest.image.repository }}:{{ .Values.services.backrest.image.tag }}"
@@ -51,6 +91,16 @@ spec:
             - name: cache
               mountPath: /cache
       volumes:
+        {{- if .Values.services.backrest.vpn.enabled }}
+        - name: wg0-conf
+          secret:
+            secretName: gluetun-wireguard-conf
+            optional: false
+        - name: dev-net-tun
+          hostPath:
+            path: /dev/net/tun
+            type: CharDevice
+        {{- end }}
         - name: userdata
           hostPath:
             path: "{{ .Values.services.backrest.userdata }}"
